### ISSUE TITLE
Websocket connection stops working

### ISSUE THREAD

**Issue by davidm-glitch** [davidm-glitch/home-assistant-eheim-digital#10]
After a while the connection breaks. We need an automatic reconnect.

![image](https://github.com/davidm-glitch/home-assistant-eheim-digital/assets/59320226/33346f31-dcb4-4025-a681-e9cc24b410e9)

**Comment by jkhalil** [comment]
commit [23e5661](https://github.com/davidm-glitch/home-assistant-eheim-digital/commit/23e56612d44a76096dfb8f7ec3042a4c67dd1a07) should fix this and was added to release [v0.1.6](https://github.com/davidm-glitch/home-assistant-eheim-digital/releases/tag/v0.1.6)

**Comment by nielsvanbaal** [comment]
> commit [23e5661](https://github.com/davidm-glitch/home-assistant-eheim-digital/commit/23e56612d44a76096dfb8f7ec3042a4c67dd1a07) should fix this and was added to release [v0.1.6](https://github.com/davidm-glitch/home-assistant-eheim-digital/releases/tag/v0.1.6)

Unfortunately I still experiencing disconnects. Reloading helps. Before upgrade to 0.1.6 it worked fine for a day with 0.1.5. But reverting back didn't help, so maybe the one working day was just luck🤔

**Comment by Destiky** [comment]
Hi, have same problem, first connection OK after some time I can't connect anymore.

**Comment by davidm-glitch** [comment]
> Hi, have same problem, first connection OK after some time I can't connect anymore.

Is it still available via Webinterface? If so, for now, try reloading the integration. We are not sure why this keeps happening.

**Comment by Destiky** [comment]
Yes the website works, I tried to uninstall and install 
'
![image](https://github.com/davidm-glitch/home-assistant-eheim-digital/assets/98362659/16f98881-0b79-4103-a0b1-a63fc83f292f)

**Comment by Destiky** [comment]
I have already purchased CO2 and I will be buying lighting as well so I will help to test

see still function
![image](https://github.com/davidm-glitch/home-assistant-eheim-digital/assets/98362659/ea648f0d-a181-43ca-8408-96dacec64a7a)

**Comment by davidm-glitch** [comment]
> Yes the website works, I tried to uninstall and install 
> '
> ![image](https://github.com/davidm-glitch/home-assistant-eheim-digital/assets/98362659/16f98881-0b79-4103-a0b1-a63fc83f292f)
> 

Try clicking the three dots and then reinitialize. Often this helps

**Comment by davidm-glitch** [comment]
> I have already purchased CO2 and I will be buying lighting as well so I will help to test
> 
> see still function
> ![image](https://github.com/davidm-glitch/home-assistant-eheim-digital/assets/98362659/ea648f0d-a181-43ca-8408-96dacec64a7a)
> 

If you like join us on our discord server, communication is a bit easier there. Invitation link can be found in the readme ;)

**Comment by Destiky** [comment]
yed, reload work but i must reloaded 5x than fix

**Comment by davidm-glitch** [comment]
will not be an issue with new api. closed
